# Generated by Django 3.0.8 on 2020-07-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='name',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
