# Generated by Django 3.0.8 on 2020-07-20 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_management', '0002_auto_20200720_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='cook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='canteen_management.Cook'),
        ),
    ]
