# Generated by Django 3.0.8 on 2020-07-22 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_management', '0003_auto_20200720_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=20)),
                ('pan_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cooks', models.ManyToManyField(to='canteen_management.Cook')),
            ],
        ),
        migrations.AddField(
            model_name='cook',
            name='cook_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='canteen_management.CookInfo'),
        ),
    ]
