# Generated by Django 3.0.8 on 2020-07-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_management', '0004_auto_20200722_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='cook'),
        ),
    ]
